[@ui.messageBox titleKey="io.blitz.docs"/]
[@ww.textfield labelKey="io.blitz.command" name="command" required='true' cssClass="long-field"/]
[@ww.textfield labelKey="io.blitz.username" name="username" required='true'/]
[@ww.textfield labelKey="io.blitz.apiKey" name="apiKey" required='true'/]
[@ww.textfield labelKey="io.blitz.percentage" name="percentage" required='true' cssClass="short-field"/]
